### ISSUE TITLE
手机锁屏后，触动精灵无法定时运行

### ISSUE THREAD

**Issue by test98123456** [chenqingspring/dd-punch#5]
Hi，最近我手机设置了触动定时运行后，发现脚本并没有跑(没有运行日志)，我打开开发者模式，设置了不锁屏，也不生效，不知道您遇到过没有

**Comment by chenqingspring** [comment]
之前遇到过一次。后来查了一下，有个release notes上说 『修复了xxx方法需要插上电源才能正常调用』，后来试了一下，果然就好了。。但是我当时用的是最新版的API。

**Comment by niguangxingzou** [comment]
哈哈，治标不治本，永远是见招拆招，但最终还是会被发现，不如试试我们的终极方案，完美破解！

**Comment by niguangxingzou** [comment]
威信见我头像。

**Comment by chenqingspring** [comment]
完美方案是换个不打卡的工作！

**Comment by niguangxingzou** [comment]
非也。你Out了，我们完美破解钉钉，任何地方都可以正常打卡！

**Comment by niguangxingzou** [comment]
谢谢，主要是没有必要一直开着

**Comment by chenqingspring** [comment]
嗯 祝你们生意兴隆
