### ISSUE TITLE
在分辨率低的手机上,触动精灵打开的是邮箱,而不是签到.

### ISSUE THREAD

**Issue by xclidongbo** [chenqingspring/dd-punch#6]
在分辨率低的手机上,触动精灵打开的是邮箱,而不是签到.

**Comment by niguangxingzou** [comment]
幸好我找到了一个另外的方法来永久代替，再也不用担心钉钉升级了，微信，陌陌，微博，各种定位通吃。真兴奋呢。

**Comment by xclidongbo** [comment]
@niguangxingzou  这个方法就是换了份工作?

**Comment by niguangxingzou** [comment]
开什么玩笑，你了解的太少啦，请睁眼看世界！我们不知道的太多了。

**Comment by kennenfromchina** [comment]
> 开什么玩笑，你了解的太少啦，请睁眼看世界！我们不知道的太多了。

现在还能用吗
